<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta charset="utf-8">
<title>Issue 397: ostream::sentry dtor throws exceptions</title>
<style type="text/css">
  p {text-align:justify}
  li {text-align:justify}
  blockquote.note
  {
    background-color:#E0E0E0;
    padding-left: 15px;
    padding-right: 15px;
    padding-top: 1px;
    padding-bottom: 1px;
  }
  ins {background-color:#A0FFA0}
  del {background-color:#FFA0A0}
  table {border-collapse: collapse;}
</style>
</head>
<body>
<p>Revised 2016-11-22 at 01:11:47 UTC</p>
<hr>
<h3><a name="397" href="397">397.</a> <tt>ostream::sentry</tt> dtor throws exceptions</h3>
<p><b>Section:</b> 27.7.3.4 [ostream::sentry] <b>Status:</b> <a href="lwg-active.html#NAD Editorial">NAD Editorial</a>
 <b>Submitter:</b> Martin Sebor <b>Opened:</b> 2003-01-05 <b>Last modified:</b> 2016-11-16</p>
<p><b>Priority: </b>Not Prioritized
</p>
<p><b>View all other</b> <a href="lwg-index.html#ostream::sentry">issues</a> in [ostream::sentry].</p>
<p><b>View all issues with</b> <a href="lwg-status.html#NAD Editorial">NAD Editorial</a> status.</p>
<p><b>Discussion:</b></p>
    <p>
17.4.4.8, p3 prohibits library dtors from throwing exceptions.
    </p>
    <p>
27.6.2.3, p4 says this about the ostream::sentry dtor:
    </p>
    <pre>
    -4- If ((os.flags() &amp; ios_base::unitbuf) &amp;&amp; !uncaught_exception())
        is true, calls os.flush().
    </pre>
    <p>
27.6.2.6, p7 that describes ostream::flush() says:
    </p>
    <pre>
    -7- If rdbuf() is not a null pointer, calls rdbuf()->pubsync().
        If that function returns ?-1 calls setstate(badbit) (which
        may throw ios_base::failure (27.4.4.3)).
    </pre>
    <p>
That seems like a defect, since both pubsync() and setstate() can
throw an exception. 
    </p>
<p><i>[
The contradiction is real.  Clause 17 says destructors may never
throw exceptions, and clause 27 specifies a destructor that does
throw.  In principle we might change either one.  We're leaning
toward changing clause 17: putting in an "unless otherwise specified"
clause, and then putting in a footnote saying the sentry destructor
is the only one that can throw.  PJP suggests specifying that
sentry::~sentry() should internally catch any exceptions it might cause.
]</i></p>


<p><i>[
See <a href="418">418</a> and <a href="622">622</a> for related issues.
]</i></p>


<p><i>[
2009-07 Frankfurt
]</i></p>


<blockquote>
<p>
Move to Review. Add "Throws: nothing" to the specification of <tt>ostream::sentry::~sentry()</tt>.
</p>
</blockquote>

<p><i>[
2009-10-13 Daniel adds:
]</i></p>


<blockquote><p>
The proposed resolution of <a href="835">835</a> is written to match the outcome
of this issue.
</p></blockquote>

<p><i>[
2009 Santa Cruz:
]</i></p>


<blockquote><p>
Move to Open.  Our intent is to solve this issue with <a href="835">835</a>.
</p></blockquote>

<p><i>[
2010-03-06 Martin updates wording.
]</i></p>


<p><i>[
2010 Pittsburgh:
]</i></p>


<blockquote><p>
Moved to NAD Editorial.
</p></blockquote>



<p><b>Rationale:</b></p>
<p>
Solved by <a href="835">835</a>.
</p>


<p><b>Proposed resolution:</b></p>
<p>
Add after 27.7.3.4 [ostream::sentry] p17:
</p>

<blockquote>
<pre>
~sentry();
</pre>
<blockquote>
<p>
-17- If <tt>(os.flags() &amp; ios_base::unitbuf)</tt>
is <tt>true</tt>, calls <tt>os.flush()</tt>.
</p>

<p><ins>
<i>Throws:</i> Nothing.
</ins></p>
</blockquote>
</blockquote>





</body>
</html>
